name: Build and Push Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]



jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t c7nasr/shortha:latest .

      - name: Push Docker image
        run: |
          docker push c7nasr/shortha:latest

      - name: Trigger Coolify Deploy + NTFY
        uses: gitnasr/coolify-trigger-deploy@v2.0.0
        with:
          docker_image: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          ntfy_topic: ${{ secrets.NTFY_TOPIC }}
          ntfy_token: ${{ secrets.NTFY_TOKEN }}
          coolify_url: ${{ secrets.COOLIFY_URL }}
          coolify_resource_id: ${{ secrets.COOLIFY_RESOURCE_ID }}
          coolify_api_token: ${{ secrets.COOLIFY_API_TOKEN }}